const state={area:'Skin',imageUrl:null,file:null,assessmentId:null,profile:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3200)}
function selectArea(area){state.area=area;$$('.area-choice button').forEach(b=>b.classList.toggle('selected',b.dataset.area===area))}
function setImage(file){if(!file||!file.type.startsWith('image/'))return toast('Choose a JPG, PNG, or WEBP image.');if(file.size>10*1024*1024)return toast('Choose an image smaller than 10 MB.');if(state.imageUrl)URL.revokeObjectURL(state.imageUrl);state.file=file;state.imageUrl=URL.createObjectURL(file);const z=$('#dropZone');z.style.backgroundImage=`url("${state.imageUrl}")`;z.classList.add('has-image');$('#analyzeButton').disabled=false;$('#stepCount').textContent='STEP 2 OF 3'}
function openProfile(){$('#profileModal').classList.add('show');$('#profileModal').setAttribute('aria-hidden','false')}function closeProfile(){$('#profileModal').classList.remove('show');$('#profileModal').setAttribute('aria-hidden','true')}function closeResult(){$('#resultModal').classList.remove('show');$('#resultModal').setAttribute('aria-hidden','true')}
function renderProducts(items,eligible){const grid=$('#productGrid');if(!eligible){grid.innerHTML='<article class="product-empty"><span>✚</span><h3>Clinical review first</h3><p>This screen is not eligible for product guidance. Please consult an RMP.</p></article>';return}grid.innerHTML=items.map(x=>`<article class="product-card"><span class="product-type">${x.category}</span><span class="consult-gate">CONSULT RMP FIRST</span><h3>${x.name}</h3><p>${x.purpose}</p><p class="guardrail">${x.guardrail}</p><button class="text-button" data-product>Discuss before use →</button></article>`).join('');$$('[data-product]').forEach(b=>b.onclick=()=>toast('Consult an RMP or pharmacist before starting any product or routine.'))}
async function loadProducts(area,score){try{const r=await fetch(`/api/products?area=${encodeURIComponent(area)}&risk_score=${score}`),d=await r.json();if(!r.ok)throw Error();renderProducts(d.items,d.eligible)}catch{toast('Product guidance is unavailable right now.')}}
function showCarePlan(plan){let box=$('#careRecommendation');if(!box){box=document.createElement('div');box.id='careRecommendation';box.className='care-recommendation';$('#researchResult').insertAdjacentElement('afterend',box)}box.innerHTML=`<span>✚</span><p><strong>${plan.heading}</strong><br>${plan.next_step}<br><em>${plan.routine_guardrail}</em></p>`}
async function analyze(){if(!state.imageUrl)return;const button=$('#analyzeButton');button.disabled=true;button.innerHTML='Reviewing <span>…</span>';const f=new FormData();[['image',state.file],['area',state.area],['duration',$('#duration').value],['discomfort',$('#discomfort').value],['change',$('#change').value],['image_context',$('#imageContext').value],['patient_id',state.profile?.patient_id||'']].forEach(([k,v])=>f.append(k,v));try{const r=await fetch('/api/assessments',{method:'POST',body:f}),d=await r.json();if(!r.ok)throw Error(d.error);state.assessmentId=d.assessment_id;const score=d.risk.score;$('#resultImage').src=state.imageUrl;$('#resultRisk').textContent=d.risk.level;$('#resultRisk').className=`risk-label ${score<40?'low':'moderate'}`;$('#findingTitle').textContent=d.screening.title;$('#findingText').textContent=d.screening.summary;$('#qualityScore').textContent=`${d.quality.score}% · ${d.quality.label}`;$('#modelStatus').textContent=`${Math.round(d.model.confidence*100)}% · screening support`;$('#clinicalStatus').textContent='Awaiting RMP review';const research=$('#researchResult');if(d.research_classifier?.available){const top=d.research_classifier.top_predictions[0];$('#researchPrediction').textContent=`${top.label} · ${Math.round(top.probability*100)}% research confidence. Not a diagnosis; only for dermatoscopic lesion images.`;research.hidden=false}else research.hidden=true;showCarePlan(d.care_plan);$('#resultModal').classList.add('show');$('#resultModal').setAttribute('aria-hidden','false');$('#stepCount').textContent='STEP 3 OF 3';loadProducts(d.area,score)}catch(e){toast(e.message||'Unable to review this image.')}button.disabled=false;button.innerHTML='Review image <span>→</span>'}
async function requestReview(){if(!state.assessmentId)return toast('Complete a screen before requesting review.');try{const r=await fetch('/api/clinical-review-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assessment_id:state.assessmentId,patient_id:state.profile?.patient_id||''})}),d=await r.json();if(!r.ok)throw Error(d.error);$('#clinicalStatus').textContent='RMP review requested';toast('Review request saved. An RMP must independently assess the concern.')}catch(e){toast(e.message||'Could not request review.')}}
async function saveProfile(e){e.preventDefault();const f=new FormData(e.currentTarget),p=Object.fromEntries(f.entries());p.health_data_consent=f.get('health_data_consent')==='on';const b=e.currentTarget.querySelector('[type="submit"]');b.disabled=true;try{const r=await fetch('/api/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw Error(d.error);state.profile=d;localStorage.setItem('dermamatrix_profile',JSON.stringify(d));$('#profileName').textContent=d.full_name;$('#profileMeta').textContent=d.patient_id;closeProfile();toast('Local profile saved.')}catch(e){toast(e.message||'Unable to save profile.')}b.disabled=false}
function restoreProfile(){try{const p=JSON.parse(localStorage.getItem('dermamatrix_profile'));if(p?.full_name){state.profile=p;$('#profileName').textContent=p.full_name;$('#profileMeta').textContent=p.patient_id}}catch{}}
$$('.area-choice button').forEach(b=>b.onclick=()=>selectArea(b.dataset.area));$('#imageInput').onchange=e=>setImage(e.target.files[0]);const drop=$('#dropZone');['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>setImage(e.dataTransfer.files[0]));$('#analyzeButton').onclick=analyze;$('#requestReviewButton').onclick=requestReview;$('#profileButton').onclick=openProfile;$('#topProfileButton').onclick=openProfile;$('#profileForm').onsubmit=saveProfile;$$('[data-close-modal]').forEach(b=>b.onclick=closeResult);$$('[data-close-profile]').forEach(b=>b.onclick=closeProfile);$('.menu-button').onclick=()=>$('.sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeResult();closeProfile()}});restoreProfile();
